################################################################################
MLI_FILE		= cordova_hot_code_push.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-hot-code-push
################################################################################
